### ISSUE TITLE
Metric scores for CQADupStack

### ISSUE THREAD

**Issue by rafaljanwojcik** [Muennighoff/sgpt#10]
Hey, what an awesome paper! I was looking for some benchmarks for semantic search and I must say it will be really useful in my research :) In this regard, I wanted to ask a question - on this page on papers with code: https://paperswithcode.com/sota/information-retrieval-on-cqadupstack you're listed as highest scoring for CQADupStack, however the metric they list there is mAP@100, and in your paper the metric listed under this score nDCG@10. Which one is correct? I'm asking, as I will be using this dataset to validate implementations of a few models, and wanted to be sure I'll be comparing correct metrics

**Comment by Muennighoff** [comment]
Thanks for noticing this!

I fixed it, so that
https://paperswithcode.com/sota/information-retrieval-on-cqadupstack now refers to the CQADupstack from USEB / TSDAE & Table 5 of SGPT

https://paperswithcode.com/sota/duplicate-question-retrieval-on-cqadupstack-1 refers to CQADupstack from BEIR & Tables 1 & 6 from SGPT.

Depending on whether you want to build symmetric or asymmetric models I would use the former or latter for benchmarking 👍

**Comment by rafaljanwojcik** [comment]
Awesome, thanks a lot! :)
